name: 'Deploy to AWS S3'
description: 'Deploy the website to an AWS S3 bucket'

runs:
  using: 'node16' # tells github that this is a js custom action, using node runtime
  main: 'main.js'
  # might need to perform pre and post steps to deploy the website (setup and cleanup)