name: 'Deploy to AWS S3'
description: 'Deploy the static website via AWS S3'


inputs:
  bucket:
    description: 'The S3 bucket name.'
    required: true

  bucket-region:
    description: 'The region of the S3 bucket'
    required: false # we make a sensible default guess regarding the region
    default: 'us-east-1'
  dist-folder: #path to the folder that contains the files that should be uplaoded to bucket
    description: 'The folder containing the deployable file'
    required: true
  
  outputs:
    website-url: 
      description: 'The URL of the deployed website'
#the syntax is the same for docker and javascript actions (in the context of the action.yml file and registering inputs and outputs)
# the difference is in how we access those inputs in the code executed in container and how we set outputs

runs:
  using: 'docker' #tells github that this is a docker action
  image: 'Dockerfile' #path to dockerfile that defines the container (public image or custom image)

